# -*- coding: UTF-8 -*-

EMPTY_STRING = u''

CAPITAL_AZ  = u'А'
SMALL_AZ    = u'а'

CAPITAL_ESTJ    = u'Е'
SMALL_ESTJ      = u'е'
SMALL_WIDE_ESTJ = u'\u0454'

AE = EMPTY_STRING.join(
    (
        CAPITAL_AZ,
        SMALL_AZ,
        CAPITAL_ESTJ,
        SMALL_ESTJ,
        SMALL_WIDE_ESTJ,
    )
)

CAPITAL_CONSONANTS  = u'БВГДЖЗЙКЛМНПРСТФХЦЧШЩЪЬ' + u'FPX' + u'\u0405'
SMALL_CONSONANTS    = u'бвгджзйклмнпрстфхцчшщъь' + u'fpx' + u'\u0455'

CAPITAL_VOWEL_DIACRITICS  = u'#$%&' + u'@' + u'\^' + u'~'
SMALL_VOWEL_DIACRITICS    = u'1234567'

CAPITAL_CONSONANT_DIACRITICS    = u''
SMALL_CONSONANT_DIACRITICS      = u''

CAPITAL_DIACRITICS  = CAPITAL_VOWEL_DIACRITICS + CAPITAL_CONSONANT_DIACRITICS
SMALL_DIACRITICS    = SMALL_VOWEL_DIACRITICS + SMALL_CONSONANT_DIACRITICS

VOWEL_DIACRITICS        = CAPITAL_VOWEL_DIACRITICS + SMALL_VOWEL_DIACRITICS
CONSONANT_DIACRITICS    = CAPITAL_CONSONANT_DIACRITICS + SMALL_CONSONANT_DIACRITICS

DIACRITICS = CAPITAL_DIACRITICS + SMALL_DIACRITICS
